### ISSUE TITLE
Release

### ISSUE THREAD

**Issue by dmhendricks** [jablonczay/code-box-copy#1]
This plugin is great - I use it regularly.

One small question: Are you at a point where you can do a release? It would allow me to simplify the jsDelivr links. For example:

```
https://cdn.jsdelivr.net/combine/gh/jablonczay/code-box-copy/clipboard/clipboard.min.js,gh/jablonczay/code-box-copy/code-box-copy/js/code-box-copy.min.js
```

...rather than:

```
https://cdn.jsdelivr.net/combine/gh/jablonczay/code-box-copy@2cc598da3bfe921cfb5a032be2ae1aae1eca4076/clipboard/clipboard.min.js,gh/jablonczay/code-box-copy@2cc598da3bfe921cfb5a032be2ae1aae1eca4076/code-box-copy/js/code-box-copy.min.js
```

Thank you,
Daniel

**Comment by jablonczay** [comment]
Hello Daniel,

I am really happy my plugin is useful for you!
Thank you for your comment! The first release is available now.

Regards,
Jablonczay

**Comment by MartinKolarik** [comment]
@jablonczay any chance you can change the version number from `v1.0` to `v1.0.0`? For the version-less urls to work the version must be a valid semver.

**Comment by jablonczay** [comment]
Sure, the version is 1.0.0 now.

**Comment by dmhendricks** [comment]
Thanks mate! We appreciate it.
