### ISSUE TITLE
Copy is not working

### ISSUE THREAD

**Issue by itsmeui** [jablonczay/code-box-copy#3]
Hi,

The plugin is working fine but copy function is not working. I tried fixing it but could not be figured out the issue.

**Comment by jablonczay** [comment]
Hi,

Thank you for your feedback! What do you see in the console, and which browser do you use?

**Comment by itsmeui** [comment]
Thanks for your reply. I am not seeing any error in the console, I am using chrome browser.

**Comment by jablonczay** [comment]
Could you share with me a public example page where I can check the issue?

**Comment by itsmeui** [comment]
Hi, I have noticed the issue. The issue is because of multiple ID's with same name

**Comment by jablonczay** [comment]
I'm glad you managed to solve the problem.
